import fs from 'node:fs'
import path from 'node:path'
import { root } from './loadSnapshot.mjs'

function mdTable(headers, rows) {
  return [
    `| ${headers.join(' | ')} |`,
    `| ${headers.map(() => '---').join(' | ')} |`,
    ...rows.map((row) => `| ${row.map((cell) => String(cell ?? '').replace(/\|/g, '\\|')).join(' | ')} |`),
  ].join('\n')
}

function rowsBySeverity(issues, severity) {
  return issues.filter((item) => item.severity === severity)
}

function ensureGeneratedDir() {
  const dir = path.join(root, '.generated/import-dry-run')
  fs.mkdirSync(dir, { recursive: true })
  return dir
}

function writeJson(filePath, value) {
  fs.writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`)
}

export function writeDryRunReport({ snapshot, payloads, validation, materialsDraft }) {
  const outPath = path.join(root, 'docs/IMPORT_DRY_RUN_REPORT.md')
  const generatedDir = ensureGeneratedDir()
  const payloadSummary = Object.fromEntries(
    Object.entries(payloads).map(([groupName, group]) => [
      groupName,
      Object.fromEntries(Object.entries(group).map(([table, rows]) => [table, rows.length])),
    ])
  )
  writeJson(path.join(generatedDir, 'payload-summary.json'), {
    generatedAt: new Date().toISOString(),
    snapshot: { source: snapshot.source, version: snapshot.version, generatedAt: snapshot.generatedAt },
    payloadSummary,
    severityCounts: validation.severityCounts,
    sourceStatusBreakdown: validation.sourceStatusBreakdown,
    resolvedMediaAliases: validation.resolvedMediaAliases.length,
    materialCandidates: materialsDraft?.materialCandidates?.length || 0,
    materialUsageRows: materialsDraft?.materialUsageRows?.length || 0,
    unresolvedMaterialLabels: materialsDraft?.unresolvedMaterialLabels?.length || 0,
  })
  writeJson(path.join(generatedDir, 'payloads.json'), payloads)
  writeJson(path.join(generatedDir, 'issues.json'), validation.issues)
  writeJson(path.join(generatedDir, 'material-candidates.json'), materialsDraft?.materialCandidates || [])
  writeJson(path.join(generatedDir, 'material-usages.json'), materialsDraft?.materialUsageRows || [])
  writeJson(path.join(generatedDir, 'material-unresolved.json'), materialsDraft?.unresolvedMaterialLabels || [])
  const groupRows = Object.entries(payloads).map(([groupName, group]) => [
    groupName,
    Object.values(group).reduce((sum, rows) => sum + rows.length, 0),
    Object.entries(group).map(([table, rows]) => `${table}: ${rows.length}`).join('<br>'),
  ])
  const issueRows = validation.issues.map((item) => [item.severity, item.area, item.message])
  const aliasRows = validation.resolvedMediaAliases.map((item) => [
    item.external_id,
    item.entity_type,
    item.entity_external_id,
    item.resolved_entity_external_id,
  ])
  const statusRows = Object.entries(validation.sourceStatusBreakdown).map(([status, count]) => [status, count])
  const materialRows = (materialsDraft?.materialCandidates || []).map((item) => [
    item.id,
    item.name,
    item.observedUsageCount,
    item.observedTotalAmount,
    item.sourceStatus,
  ])
  const unresolvedMaterialRows = (materialsDraft?.unresolvedMaterialLabels || []).map((item) => [
    item.label,
    item.observedUsageCount,
    item.observedTotalAmount,
    item.characters.join(', '),
  ])

  const content = `# Import Dry-Run Report

Date: 2026-05-16

Generated by \`npm.cmd run import:dry-run\`.

## Snapshot

- Loader: \`${snapshot.source}\`
- Snapshot version: \`${snapshot.version ?? 'unknown'}\`
- Snapshot generatedAt: \`${snapshot.generatedAt ?? 'unknown'}\`
- Loader warning: ${snapshot.loaderWarning ? `\`${snapshot.loaderWarning}\`` : 'none'}

## Summary

${mdTable(['Severity', 'Count'], Object.entries(validation.severityCounts))}

## Future SQL Payload Counts

${mdTable(['Group', 'Rows', 'Tables'], groupRows)}

## Source Status Breakdown

${statusRows.length ? mdTable(['source_status', 'Rows'], statusRows) : 'No source_status rows found.'}

## Material Extraction Draft

- Material candidates found: ${materialsDraft?.materialCandidates?.length || 0}
- Material usage rows found: ${materialsDraft?.materialUsageRows?.length || 0}
- Unresolved material labels found: ${materialsDraft?.unresolvedMaterialLabels?.length || 0}
- Source status for candidates: \`needs_verification\`
- Output is draft-only and not production import-ready.

${materialRows.length ? mdTable(['Material id', 'Name', 'Usage rows', 'Observed amount', 'source_status'], materialRows) : 'No material candidates found.'}

## Unresolved Material Labels

${unresolvedMaterialRows.length ? mdTable(['Label', 'Usage rows', 'Observed amount', 'Characters'], unresolvedMaterialRows) : 'No unresolved material labels found.'}

## Source Verification Summary

- Verified material candidates: ${materialsDraft?.sourceVerificationSummary?.verified || 0}
- Needs verification material records: ${materialsDraft?.sourceVerificationSummary?.needsVerification || 0}
- Cartridge compatible shapes remain \`needs_verification\` until trusted source evidence exists.

## Resolved Media Aliases

${aliasRows.length ? mdTable(['Media external_id', 'Entity type', 'Original entity id', 'Resolved entity id'], aliasRows) : 'No media aliases resolved.'}

## Issues

${issueRows.length ? mdTable(['Severity', 'Area', 'Message'], issueRows) : 'No issues reported.'}

## What Would Be Safe To Import Now

- Core taxonomy payloads can be used as a draft seed baseline.
- Media payloads can be imported if \`resolved_entity_external_id\` is used for canonical linking and original filename ids are preserved.
- Weapons/arcs are structurally importable as text-first records with effect JSON left empty.
- Vehicles are structurally importable.
- Official tier list rows are structurally importable because character references resolve.

## What Should Not Be Imported Yet

- Cartridge compatible shapes as verified data. They must remain \`needs_verification\`.
- Material catalog rows; the catalog is draft-only and still needs source verification.
- Placeholder Guides, Community, and Apartments as production content.
- localStorage Admin Mode overrides without a review/export workflow.
- personal Build Planner drafts or personal tier lists without user consent and real accounts.

## Next Steps

- Review generated artifacts in \`.generated/import-dry-run/\` if needed.
- Verify cartridge shape compatibility from a trusted source.
- Review material candidates, unresolved labels, and source evidence.
- Add a true dry-run SQL writer only after a migration runner/ORM is chosen.
`
  fs.writeFileSync(outPath, content)
  return outPath
}
